blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^p/(?P<post_id>[0-9]+)/$', views.detail, name='detail'),
]

pythonblogging/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('blog.urls', namespace="blog")),
]

admin.site.site_title = 'Blog Admin Interface'
admin.site.site_header = 'Blog Administration'

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class Post(models.Model):
	author = models.ForeignKey(User)
	pub_date = models.DateTimeField('date published', default=datetime.now)
	post_text = models.CharField(max_length=5000)
	post_title = models.CharField(max_length=200, default="")
	published = models.BooleanField(default=False)

	MARKDOWN = 'M'
	HTML = 'H'
	edit_choices = (
		(MARKDOWN, 'Markdown'),
		(HTML, 'HTML'),
	)
	edit_type = models.CharField(max_length=1, choices=edit_choices, default=MARKDOWN)

	def __str__(self):
		return self.post_title

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Post

# Create your views here.
def index(request):
	latest_post_list = Post.objects.filter(published=True).order_by('-pub_date')

	# If you want to display more than 5 posts per page simply change this number
	paginator = Paginator(latest_post_list, 5)

	page = request.GET.get('page')

	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page
		posts = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results
		posts = paginator.page(paginator.num_pages)

	context = {'posts': posts}
	return render(request, 'blog/index.html', context)

def detail(request, post_id):
	post = get_object_or_404(Post.objects.filter(published=True), pk=post_id)
	return render(request, 'blog/detail.html', {'post': post})

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head!!!!!! -->
	<meta name="description" content="Elijah Grubb's blog on his development experiences">
	<meta name="author" content="Elijah Grubb, judgegrubb">

	<title>{% block title %}{% endblock %} | grubbit.net</title>
	
	<!-- Bootstrap -->
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />

	<!-- Personal Stylesheet -->
	{% load staticfiles %}

	<link rel="icon" href="{% static 'blog/images/favicon.ico' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<!-- background image -->
	<img src="{% static 'blog/images/forest.jpg' %}" class="background" alt="ERROR" />

	<header>
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% block homelink %}#{% endblock %}">Elijah Grubb's Blog</a>
				</div>
				<div id="navbar" class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li><a href="http://www.grubbit.net">My Homepage</a></li>
						<li><a href="https://www.github.com/judgegrubb">My GitHub</a></li>
						<li><a href="https://www.linkedin.com/in/elijahgrubb">My LinkedIn</a></li>
						<li><a href="https://www.twitter.com/judgegrubb">My Twitter</a></li>
						<li><a href="https://www.facebook.com/ElijahLloydGrubb">My Facebook</a></li>
						<li class="{% block blogactive %}active{% endblock %}"><a href="{% block homelinktwo %}#{% endblock %}">My Blog</a></li>
					</ul>
				</div>
			</div>
		</nav>
	</header>

	<div class="main">
		<div class="content">
			{% block content %}
			{% endblock %}
		</content>

		<footer>
			{% block footer %}
			{% endblock %}
			<p>Brought to you by Elijah Grubb</p>
			<p>Code hosted on <a href="http://www.github.com/judgegrubb/python-blogging/">GitHub</a></p>
			<p>Website hosted on <a href="http://www.heroku.com/">Heroku</a></p>
			<p>Domain purchased through <a href="http://www.hover.com/">Hover</a></p>
			<p>Background courtesy of <a href="https://unsplash.com">Unsplash</a></p>
		</footer>
	</div>	


	<!-- javascript stuff placed towards end of file so page loads faster -->
	<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}

{% block title %}{{ post.post_title }}{% endblock %}

{% block homelink %}/{% endblock %}
{% block homelinktwo %}/{% endblock %}
{% block blogactive %}{% endblock %}

{% block content %}

<div class="title">
	<h1>{{ post.post_title }}</h1>
</div>

<article>
	{% ifequal post.edit_type 'H' %}
		{{ post.post_text|safe }}
	{% else %}
		{{ post.post_text }}
	{% endifequal %}
	<hr>
	<sub>{{ post.pub_date }} | {{ post.author }}</sub>
</article>

{% endblock %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block title %}blog{% endblock %}

{% block homelink %}#{% endblock %}
{% block homelinktwo %}#{% endblock %}

{% block content %}

{% if posts %}
	{% for post in posts %}
		<div class="title">
			<h1><a href="{% url 'blog:detail' post.id %}">{{ post.post_title }}</a></h1>
		</div>

		<article>
			<section>
				{% ifequal post.edit_type 'H' %}
					{{ post.post_text|safe }}
				{% else %}
					{{ post.post_text }}
				{% endifequal %}
			</section>
			<hr />
			<sub>{{ post.pub_date }} | {{ post.author }}</sub>
		</article>
	{% endfor %}
{% else %}
	<div class="title"><h1>There are no posts on this blog yet.</h1></div>
{% endif %}
{% endblock %}

{% block footer %}
	<div class="pagination">
		<span class="step-links">
			{% if posts.has_previous %}
				<a href="?page={{ posts.previous_page_number }}">previous</a>
			{% endif %}

			<span class="current">
				Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
			</span>

			{% if posts.has_next %}
				<a href="?page={{ posts.next_page_number }}">next</a>
			{% endif %}
		</span>
	</div>
{% endblock %}